name: LibreHeads
version: '${version}'
main: org.libregalaxy.libreheads.LibreHeads
api-version: 1.19
author: ItsMCB
libraries:
  - com.fasterxml.jackson.core:jackson-core:2.13.0
  - com.fasterxml.jackson.core:jackson-databind:2.13.0
  - com.fasterxml.jackson.core:jackson-annotations:2.13.0
depend:
  - VexelCore